[package]
name = "isprime"
version = "0.1.0"
edition = "2021"
description = "Quickly check if a number is prime"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ellygaytor/isprime"
repository = "https://github.com/ellygaytor/isprime"

[dependencies]
